FROM golang:1.22-bookworm

WORKDIR /app

RUN go install github.com/air-verse/air@v1.52.3 \
    && go install github.com/go-delve/delve/cmd/dlv@v1.22.1

COPY go.mod go.sum* ./
RUN go mod download

COPY . .

EXPOSE 8080 2345

CMD ["sh", "-c", "go mod tidy && air -c .air.toml"]
